In [2]:
import pandas as pd

df = pd.read_csv('weather_data_new.csv')
df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  no event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny
6  1/6/2017           34     -88888  no event

In [ ]:
import numpy as np
df.replace([-99999, -88888], np.nan)

In [ ]:
df.replace({
    'temperature': -99999,
    'windspeed': [-99999, -88888],
    'event': 'no event'
    
},np.nan)

In [ ]:
df.replace({
    -99999: np.nan,
    -88888: np.nan,
    'no event': 'Sunny'
    
})

In [3]:
df = pd.DataFrame({
    'score': ['exceptional', 'average', 'good', 'poor', 'average', 'exceptional'],
    'student': ['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica']
})
df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [5]:
df.replace(to_replace=['poor', 'average', 'good', 'exceptional'],value=[1,2,3,4])

  score  student
0     4      rob
1     2     maya
2     3  parthiv
3     1      tom
4     2   julian
5     4    erica